### ISSUE TITLE
Implement book list component

### ISSUE THREAD

**Issue by garlontas** [PickwickSoft/libraary#6]
_Note: Please close PR #5 before working on this issue_

The book model, service, routing, and module already exist. Now we want to display the books in the book list component (https://github.com/PickwickSoft/libraary/tree/main/src/main/webapp/app/librarian/book/list).

We want to retrieve the books from the service and display them in a list similar to the user management.

**Comment by s4shantanu** [comment]
Hey Garlontas,
I want to work on this issue can you just share more information with me like you have a book list or what ?

**Comment by garlontas** [comment]
Hi @s4shantanu, 
We are happy you are interested in Libraary :smiley: Unfortunately this issue is already assigned to @andryjurca.
